name: Bluemarble Retail Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        continue-on-error: true

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      # - name: Set up Android SDK
      #   uses: android-actions/setup-android@v2
      #   with:
      #     api-level: 28
      #     build-tools: 28.0.3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        continue-on-error: true

      - name: Build Debug
        run: ./gradlew clean assembleDebug --stacktrace
        continue-on-error: true

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v4.4.3
      #   with:
      #     name: APK
      #     path: ${{github.workspace}}/build/outputs/apk/release/*.apk
      #     if-no-files-found: error
      #     retention-days: 1

  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        continue-on-error: true

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
        continue-on-error: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 28
          build-tools: 28.0.3
        continue-on-error: true

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        continue-on-error: true

      - name: Run Unit Tests
        run: ./gradlew test
        continue-on-error: true

  deploy:
    #if: github.ref_type == 'tag'
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: bash $HOME/Documents/Android/cotsdeploy.sh
        continue-on-error: true
