name: First Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up cowsay
      run: sudo apt-get install -y cowsay

    - name: Run cowsay
      run: cowsay -f dragon "Run for cover, I am a Dragon" >> dragon.txt

    - name: Verify dragon.txt
      run: cat dragon.txt

    - name: Run grep
      run: grep -i "dragon" dragon.txt