name: Multi Job Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v4

    - name: Execute Cowsay CMD
      run: sudo apt-get install cowsay -y

    - name: Run cowsay
      run: cowsay -f dragon "Run for cover, I am a Dragon" >> dragon.txt

    # - name: Sleep for 30 Seconds
    #   run: sleep 30

    - name: Upload Dragin Text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt

  

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Download Drago  n Text file
      uses: actions/download-artifact@v4
      with:
          name: dragon-text-file
  

    - name: Text file Exists
      run: grep -i "dragon" dragon.txt


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:

    - name: Download Dragon Text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file

    - name: Repo File
      run: cat dragon.txt

    - name: Deploy
      run: echo Deploying..... ... ..


