# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go Version
      run: go version

    - name: Install Dependencies
      continue-on-error: true
      run: |
          go get .
          go get example.com/octo-examplemodule
          go get example.com/octo-examplemodule@v1.3.4

    - name: Build
      continue-on-error: true
      run: go build -v ./...
    - name: Test with the Go CLI
      continue-on-error: true
      run: go test -json > TestResults-${{ matrix.go-version }}.json

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json


