name: Pull Request Review
on:
    pull_request_review: 
        types: 
            submitted

jobs:
    approved:
        if: github.event.review.state == 'approved'
        runs-on: ubuntu-latest
        steps:
        - run: echo "The PR is reviewed"