name: Runner Context
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Build with logs
          run: |
            mkdir ${{ runner.temp }}/build_logs
            echo "Logs from building" >> ${{ runner.temp }}/build_logs/build.log
            exit 1

        - name: Upload logs to fail
          if: failure()
          uses: actions/upload-artifacts@v4
          with:
            name: Build failure logs
            path: ${{ runner.temp }}/build_logs