name: Shared Matrix
on:
    push: 
    workflow_dispatch: 

jobs:
    define-matrix:
        runs-on: ubuntu-latest
        outputs:
          colors: ${{ steps.colors.outputs.colors }}
        steps:
        - name: Define Colors
          id: colors
          run: |
            echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

    produce-artifacts:
        runs-on: ubuntu-latest
        needs: define-matrix
        strategy:
          matrix:
            color: ${{ fromJson(needs.define-matrix.outputs.colors) }}
        steps:
        - name: Define Color
          env:
            color: ${{ matrix.color }}
          run: |
            echo "$color" > color

        - name: Upload Artifacts
          uses: actions/upload-artifacts@v4
          with:
            name: ${{ matrix.color }}
            path: color

    consume-artifacts:
        runs-on: ubuntu-latest
        needs: [define-matrix,produce-artifacts]
        strategy:
          matrix:
            color: ${{ fromJson(needs.define-matrix.outputs.colors) }}
        steps:

        - name: Download Artifacts
          uses: actions/download-artifacts@v4
          with:
            name: ${{ matrix.color }}
            path: color

        - name: Report Color            
          run: |
              cat color

          


    